name: buf
on:
  push:
    branches:
      - main
jobs:
  buf:
    name: push Buf modules to BSR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c
        with:
          format: false
          lint: false
          breaking: false
          pr_comment: false
          token: ${{ secrets.BUF_TOKEN }}
          input: proto
