name: lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639
        with:
          go-version-file: ./go.mod
      - name: install tools
        run: make tools
      - name: build tools
        run: make build
      - name: run lint
        run: make lint
